# Generated by Django 4.2 on 2024-05-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_subject_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='days',
            field=models.CharField(default='{"0": [], "1": [], "2": [], "3": [], "4": [], "5": [], "6": [], "7": [], "8": []}', max_length=512),
        ),
        migrations.CreateModel(
            name='AttendanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
