# Generated by Django 4.2 on 2024-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_subject_days_attendanceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markitem',
            name='mark',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='AttendanceItem',
        ),
    ]
