# Generated by Django 4.2 on 2024-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_markitem_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markitem',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
